 # Find all the available rules by running:
 # swiftlint rules

disabled_rules:
- type_name
- force_try
- force_cast
- empty_count
- file_length
- identifier_name
- force_unwrapping
- type_body_length
- shorthand_operator
- trailing_whitespace
- function_body_length
- cyclomatic_complexity

line_length: 200

# some rules are only opt-in
opt_in_rules:
 #- closure_end_indentation
 - closure_spacing
 #- conditional_returns_on_newline
 - explicit_init
 #- explicit_top_level_acl
 #- explicit_type_interface
 - extension_access_modifier
 - fatal_error_message
 - first_where
 #- implicit_return
 - implicitly_unwrapped_optional
 - multiline_parameters
 - nimble_operator
 #- no_extension_access_modifier
 #- number_separator
 - object_literal
 - operator_usage_whitespace
 - overridden_super_call
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 #- sorted_imports
 - switch_case_on_newline
 #- vertical_parameter_alignment_on_call
 - empty_count
 - missing_docs
 - force_unwrapping

# exclude projects & frameworks integrated through carthage/cocoapods
excluded:
 - Carthage
 - Pods
 - vendor
 - External
